# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2569bf4491968e5eddab74ba23bd5f4668ddc2fd639984c87d2a1d4f648ea39efb853b2f7775ed2c3fa2ef14267e6aa5ce3bd65afa044bfc8e23934255c1a8f1

test:
  secret_key_base: b8f6cb1aed013be1c74f7fe8f0087a9f658b8b13e91bdd87cd911f88cf021df3461bfc1b25c8f53fa8bf41422f6a844ba2cb059fe9908b44ee68e0ea6690a87c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
